### ISSUE TITLE
MasterPageTracker cannot be added to Layout without error

### ISSUE THREAD

**Issue by kcalongne** [mendix/GoogleAnalytics#16]
Using Mendix 7.11 and GoogleAnalytics v3.3.4. Adding the MasterPageTracker to a Layout gives error, "Move this widget into a data container, for example a data view or list view." Adding data view to a layout is not possible. Is there a new way the MasterPageTracker widget should be added to a project?

![image](https://user-images.githubusercontent.com/11686815/36218019-acbdefe6-1178-11e8-9754-4427a33699af.png)

**Comment by Andries-Smit** [comment]
The Master Page Tracker requires context, so it should be placed inside data view.
