### ISSUE TITLE
Resolve deprecation warnings in console

### ISSUE THREAD

**Issue by johanflikweert** [mendix/GoogleAnalytics#18]
Using the EventTrackerButton, the browser's console is logged with the following 2 deprecation warnings. To make the widget future proof, they should be resolved.
```
DEPRECATED: _FormBase.save will be removed in version 8.0. The 'save' message for Forms does not have any effect anymore. To trigger a Form submit, it's enough to only call the 'commit' method on a Form instead.
DEPRECATED: store.caller argument of mx.data.action will be removed in version 8.0. The originating page should be passed to mx.data.action as 'origin' instead.
```

**Comment by Andries-Smit** [comment]
Update version, does not show deprecations.  The Google Analytics widget version 3.3.5 is now available in the app store https://appstore.home.mendix.com/link/app/105/
