### ISSUE TITLE
MasterPageTracker doesn't work in Phonegap app

### ISSUE THREAD

**Issue by a-takashima-k** [mendix/GoogleAnalytics#20]
I am using Google Analytics with my phonegap application.
AdvancedPageTracker is working normally in Phonegap app. However MasterPageTracker did not work.
I think that it is necessary to apply the correction in Issue #15 also to MasterPageTracker.js.

**Comment by Andries-Smit** [comment]
We changed to protocol to https, which should fix this issue. The Google Analytics widget version 3.3.5 is now available in the app store https://appstore.home.mendix.com/link/app/105/
