### ISSUE TITLE
Mx8 compatibility

### ISSUE THREAD

**Issue by WiekeBouten** [mendix/GoogleAnalytics#21]
In Mendix 8 the widget breaks, giving error message CE6508: "Version 3.3.4 of the 'MasterPageTracker' widget is not compatible with this Mendix version. Update the widget with the latest version from the App Store." version 3.3.4 however is the latest version from the app store.

**Comment by robertprice** [comment]
We've just hit this issue as well. Any idea how to fix?

**Comment by robertprice** [comment]
Our quick fix for this was to remove the appstore.id from the .mpk and bump the version to 3.3.5. This means it no longer looks at the App Store and seems to work. This may be flagged on the App Store as not for Mendix 8.

**Comment by Andries-Smit** [comment]
The Google Analytics widget version 3.3.5 is now available in the app store https://appstore.home.mendix.com/link/app/105/
