### ISSUE TITLE
EventTrackerButton doesn't pass enclosing Entity

### ISSUE THREAD

**Issue by kcalongne** [mendix/GoogleAnalytics#4]
Hello,

I've tested this several times with both persistent and non-persistent entities. The object param for the EventTrackerButton microflow is always null causing the microflow to fail.

edit (more info): widget version: v3.1  modeler: 5.21.1

**Comment by JelteMX** [comment]
Can you please elaborate on this issue? So what are the steps and where does it fail?

**Comment by kcalongne** [comment]
Hi Jelte and thanks for responding!

I have a EventTrackerButton widget inside of a templage grid. The On Click microflow has the correct Security Roles set and The microflow functions properly outside of the eventTrackerButton.

I've included a screenshot of my debug variables to show that the microflow argument from the parent entity is not getting passed into the microflow.

![eventtrackerbug0](https://cloud.githubusercontent.com/assets/11686815/13115750/ae652fba-d55e-11e5-81ee-fc3bc54a53e2.png)

![eventtrackerbug1](https://cloud.githubusercontent.com/assets/11686815/13115627/22656cd2-d55e-11e5-9665-0969efeb16a7.png)

Thank you for your help!

**Comment by JelteMX** [comment]
Got it! I have found the bug in https://github.com/mendix/GoogleAnalytics/blob/master/src/GoogleAnalytics/widget/EventTrackerButton.js#L98 and reproduced your issue.

This is old code, we have a new way of calling a microflow. We'll update this as soon as possible

**Comment by JelteMX** [comment]
Issue fixed and included on the App Store :-) https://appstore.home.mendix.com/link/app/105/Mendix/Google-Analytics

**Comment by kcalongne** [comment]
Thanks so much, Jelte!
