### ISSUE TITLE
EventTrackerButton doesn't Action attribute to Google

### ISSUE THREAD

**Issue by kcalongne** [mendix/GoogleAnalytics#6]
Hello,

After entering Action information into the EventTrackerButton widget, executing the microflow, and then viewing the event in Google Analytics' Dashboard the Action information is not showing in GA.

I have not verified if the Label or Value params are being passed into GA.

please see screen shots for examples

THANKS!!!

Modeler version 5.21.1
widget version 3.2.1

![ga1](https://cloud.githubusercontent.com/assets/11686815/13153454/d71cf98e-d639-11e5-8835-0483d19498ae.png)

![ga2](https://cloud.githubusercontent.com/assets/11686815/13153457/dbbd470a-d639-11e5-90ea-213cd2f3e978.png)

**Comment by JelteMX** [comment]
I'll check later on if that's the case. Looking at the code it seems to send the event when you click it. It will pass on the Label & Value if available. 

Check it again a little later... The events are not realtime in Google, so it might take a little while for them to show up in Google Analytics. Try to check whether you can see the events coming in at the Realtime tab of Analytics

**Comment by JelteMX** [comment]
There was indeed a small issue with the button, it used the wron key. We have fixed it, will update it in the AppStore
